import{S as f,a as p}from"./assets/vendor-58e78301.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))o(r);new MutationObserver(r=>{for(const t of r)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&o(a)}).observe(document,{childList:!0,subtree:!0});function e(r){const t={};return r.integrity&&(t.integrity=r.integrity),r.referrerPolicy&&(t.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?t.credentials="include":r.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(r){if(r.ep)return;r.ep=!0;const t=e(r);fetch(r.href,t)}})();function h(c){const n=document.querySelector(".gallery");n.innerHTML="",c.forEach(e=>{const o=document.createElement("div");o.classList.add("image-card"),e.webformatURL;const r=e.largeImageURL;e.tags;const t=e.likes,a=e.views,d=e.comments,m=e.downloads,i=document.createElement("img");i.classList.add("img"),i.src=e.webformatURL,i.alt=e.tags,i.style.width="100%";const l=document.createElement("div");l.classList.add("image-info"),l.innerHTML=`
    <p class="info-item">Likes:<br>${t}</p>
    <p class="info-item">Views:<br>${a}</p>
    <p class="info-item">Comments:<br>${d}</p>
    <p class="info-item">Downloads:<br>${m}</p>
  `;const s=document.createElement("a");s.href=r,s.classList.add("gallery-item"),s.style.textDecoration="none",s.appendChild(i),s.appendChild(l),o.appendChild(s),n.appendChild(o)}),y()}function y(){new f(".gallery-item").refresh()}function g(c){const n=document.querySelector(".gallery");c.forEach(e=>{const o=document.createElement("div");o.classList.add("image-card"),e.webformatURL;const r=e.largeImageURL;e.tags;const t=e.likes,a=e.views,d=e.comments,m=e.downloads,i=document.createElement("img");i.classList.add("img"),i.src=e.webformatURL,i.alt=e.tags,i.style.width="100%";const l=document.createElement("div");l.classList.add("image-info"),l.innerHTML=`
    <p class="info-item">Likes:<br>${t}</p>
    <p class="info-item">Views:<br>${a}</p>
    <p class="info-item">Comments:<br>${d}</p>
    <p class="info-item">Downloads:<br>${m}</p>
  `;const s=document.createElement("a");s.href=r,s.classList.add("gallery-item"),s.style.textDecoration="none",s.appendChild(i),s.appendChild(l),o.appendChild(s),n.appendChild(o)}),y()}let u=1;async function b(){const n=document.querySelector(".searchInput").value.trim(),e=document.querySelector(".loader"),o=document.querySelector(".gallery");if(n==="")return iziToast.show({message:"Please enter a keyword",backgroundColor:"yellow"}),Promise.reject("Empty query");const t=`https://pixabay.com/api/?key=42324270-89622daef349524aeb531ebd1&q=${n}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=${u}`;e.style.display="inline-block",o.innerHTML="";try{const a=await p.get(t);e.style.display="none",!a.data.hits||a.data.hits.length===0?iziToast.error({color:"#fafafb",backgroundColor:"#ef4040",message:"Sorry, there are no images matching your search query. Please try again!"}):h(a.data.hits)}catch(a){e.style.display="none",iziToast.error({title:"Error!",message:`An error occurred while fetching data: ${a.message}. Please try again later.`})}}async function L(){u+=1,document.querySelector(".gallery");const c=document.querySelector(".loader"),r=`https://pixabay.com/api/?key=42324270-89622daef349524aeb531ebd1&q=${document.querySelector(".searchInput").value.trim()}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=${u}`;try{const t=await p.get(r,{cache:"no-cache"});c.style.display="none",!t.data.hits||t.data.hits.length===0?iziToast.error({color:"#fafafb",backgroundColor:"#ef4040",message:"Sorry, there are no images matching your search query. Please try again!"}):g(t.data.hits)}catch(t){c.style.display="none",iziToast.error({title:"Error!",message:`An error occurred while fetching data: ${t.message}. Please try again later.`})}}const w=document.querySelector(".searchForm");w.addEventListener("submit",function(c){c.preventDefault(),b()});const E=document.querySelector(".loadMoreButton");E.addEventListener("click",L);
//# sourceMappingURL=commonHelpers.js.map
