import{S as h,a as y}from"./assets/vendor-58e78301.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();function g(r){const s=document.querySelector(".gallery");s.innerHTML="",r.forEach(e=>{const n=document.createElement("div");n.classList.add("image-card"),e.webformatURL;const t=e.largeImageURL;e.tags;const o=e.likes,i=e.views,l=e.comments,m=e.downloads,c=document.createElement("img");c.classList.add("img"),c.src=e.webformatURL,c.alt=e.tags,c.style.width="100%";const d=document.createElement("div");d.classList.add("image-info"),d.innerHTML=`
    <p class="info-item">Likes:<br>${o}</p>
    <p class="info-item">Views:<br>${i}</p>
    <p class="info-item">Comments:<br>${l}</p>
    <p class="info-item">Downloads:<br>${m}</p>
  `;const a=document.createElement("a");a.href=t,a.classList.add("gallery-item"),a.style.textDecoration="none",a.appendChild(c),a.appendChild(d),n.appendChild(a),s.appendChild(n)}),p()}function p(){new h(".gallery-item").refresh()}function b(r){const s=document.querySelector(".gallery");r.forEach(e=>{const n=document.createElement("div");n.classList.add("image-card"),e.webformatURL;const t=e.largeImageURL;e.tags;const o=e.likes,i=e.views,l=e.comments,m=e.downloads,c=document.createElement("img");c.classList.add("img"),c.src=e.webformatURL,c.alt=e.tags,c.style.width="100%";const d=document.createElement("div");d.classList.add("image-info"),d.innerHTML=`
    <p class="info-item">Likes:<br>${o}</p>
    <p class="info-item">Views:<br>${i}</p>
    <p class="info-item">Comments:<br>${l}</p>
    <p class="info-item">Downloads:<br>${m}</p>
  `;const a=document.createElement("a");a.href=t,a.classList.add("gallery-item"),a.style.textDecoration="none",a.appendChild(c),a.appendChild(d),n.appendChild(a),s.appendChild(n)}),p()}let u=1;async function w(){const s=document.querySelector(".searchInput").value.trim(),e=document.querySelector(".loader"),n=document.querySelector(".gallery"),t=document.querySelector(".load-more-button");if(s==="")return iziToast.show({message:"Please enter a keyword",backgroundColor:"yellow"}),Promise.reject("Empty query");const i=`https://pixabay.com/api/?key=42324270-89622daef349524aeb531ebd1&q=${s}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=${u}`;e.style.display="inline-block",n.innerHTML="";try{const l=await y.get(i);e.style.display="none",!l.data.hits||l.data.hits.length===0?iziToast.error({color:"#fafafb",backgroundColor:"#ef4040",message:"Sorry, there are no images matching your search query. Please try again!"}):(g(l.data.hits),t.style.visibility="visible")}catch(l){e.style.display="none",iziToast.error({title:"Error!",message:`An error occurred while fetching data: ${l.message}. Please try again later.`})}}async function L(){u+=1;const r=document.querySelector(".loader"),t=`https://pixabay.com/api/?key=42324270-89622daef349524aeb531ebd1&q=${document.querySelector(".searchInput").value.trim()}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=${u}`;try{const o=await y.get(t,{cache:"no-cache"});if(r.style.display="none",!o.data.hits||o.data.hits.length===0)iziToast.error({color:"#fafafb",backgroundColor:"#ef4040",message:"Sorry, there are no images matching your search query. Please try again!"});else{b(o.data.hits);const i=o.data.totalHits||0;if(u*15>=i){const m=document.querySelector(".loadMoreButton");m.style.display="none",iziToast.info({message:"We're sorry, but you've reached the end of search results."})}C()}}catch(o){r.style.display="none",iziToast.error({title:"Error!",message:`An error occurred while fetching data: ${o.message}. Please try again later.`})}}function C(){const r=document.querySelector(".gallery"),s=q(r);window.scrollBy({top:s*2,behavior:"smooth"})}function q(r){return r.querySelector(".image-card").getBoundingClientRect().height}const E=document.querySelector(".searchForm"),f=document.querySelector(".load-more-button");f.style.visibility="hidden";E.addEventListener("submit",function(r){r.preventDefault(),w()});f.addEventListener("click",L);
//# sourceMappingURL=commonHelpers.js.map
