import{S as b,a as y}from"./assets/vendor-58e78301.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))s(o);new MutationObserver(o=>{for(const t of o)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function e(o){const t={};return o.integrity&&(t.integrity=o.integrity),o.referrerPolicy&&(t.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?t.credentials="include":o.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(o){if(o.ep)return;o.ep=!0;const t=e(o);fetch(o.href,t)}})();function w(r){const n=document.querySelector(".gallery");n.innerHTML="",r.forEach(e=>{const s=document.createElement("div");s.classList.add("image-card"),e.webformatURL;const o=e.largeImageURL;e.tags;const t=e.likes,a=e.views,u=e.comments,d=e.downloads,i=document.createElement("img");i.classList.add("img"),i.src=e.webformatURL,i.alt=e.tags,i.style.width="100%";const l=document.createElement("div");l.classList.add("image-info"),l.innerHTML=`
    <p class="info-item">Likes:<br>${t}</p>
    <p class="info-item">Views:<br>${a}</p>
    <p class="info-item">Comments:<br>${u}</p>
    <p class="info-item">Downloads:<br>${d}</p>
  `;const c=document.createElement("a");c.href=o,c.classList.add("gallery-item"),c.style.textDecoration="none",c.appendChild(i),c.appendChild(l),s.appendChild(c),n.appendChild(s)}),p()}function p(){new b(".gallery-item").refresh()}function L(r){const n=document.querySelector(".gallery");r.forEach(e=>{const s=document.createElement("div");s.classList.add("image-card"),e.webformatURL;const o=e.largeImageURL;e.tags;const t=e.likes,a=e.views,u=e.comments,d=e.downloads,i=document.createElement("img");i.classList.add("img"),i.src=e.webformatURL,i.alt=e.tags,i.style.width="100%";const l=document.createElement("div");l.classList.add("image-info"),l.innerHTML=`
    <p class="info-item">Likes:<br>${t}</p>
    <p class="info-item">Views:<br>${a}</p>
    <p class="info-item">Comments:<br>${u}</p>
    <p class="info-item">Downloads:<br>${d}</p>
  `;const c=document.createElement("a");c.href=o,c.classList.add("gallery-item"),c.style.textDecoration="none",c.appendChild(i),c.appendChild(l),s.appendChild(c),n.appendChild(s)}),p()}let m=1;const q=document.querySelector(".searchForm"),E=document.querySelector(".load-more-button");q.addEventListener("submit",async r=>{r.preventDefault(),await h(),f()});E.addEventListener("click",async()=>{await g()});function f(){const r=document.querySelector(".load-more-button");r.style.display="inline-block"}async function h(){const n=document.querySelector(".searchInput").value.trim(),e=document.querySelector(".loader"),s=document.querySelector(".gallery");if(n==="")return iziToast.show({message:"Please enter a keyword",backgroundColor:"yellow"}),Promise.reject("Empty query");const t=`https://pixabay.com/api/?key=42324270-89622daef349524aeb531ebd1&q=${n}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=${m}`;e.style.display="inline-block",s.innerHTML="";try{const a=await y.get(t);e.style.display="none",!a.data.hits||a.data.hits.length===0?iziToast.error({color:"#fafafb",backgroundColor:"#ef4040",message:"Sorry, there are no images matching your search query. Please try again!"}):(w(a.data.hits),f())}catch(a){e.style.display="none",iziToast.error({title:"Error!",message:`An error occurred while fetching data: ${a.message}. Please try again later.`})}}async function g(){m+=1;const r=document.querySelector(".loader"),o=`https://pixabay.com/api/?key=42324270-89622daef349524aeb531ebd1&q=${document.querySelector(".searchInput").value.trim()}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=${m}`;try{const t=await y.get(o,{cache:"no-cache"});if(r.style.display="none",!t.data.hits||t.data.hits.length===0)iziToast.error({color:"#fafafb",backgroundColor:"#ef4040",message:"Sorry, there are no images matching your search query. Please try again!"});else{L(t.data.hits);const a=t.data.totalHits||0;if(m*15>=a){const d=document.querySelector(".loadMoreButton");d.style.display="none",iziToast.info({message:"We're sorry, but you've reached the end of search results."})}C()}}catch(t){r.style.display="none",iziToast.error({title:"Error!",message:`An error occurred while fetching data: ${t.message}. Please try again later.`})}}function C(){const r=document.querySelector(".gallery"),n=S(r);window.scrollBy({top:n*2,behavior:"smooth"})}function S(r){return r.querySelector(".image-card").getBoundingClientRect().height}const v=document.querySelector(".searchForm");v.addEventListener("submit",function(r){r.preventDefault(),h()});const $=document.querySelector(".load-more-button");$.addEventListener("click",g);
//# sourceMappingURL=commonHelpers.js.map
